version: "3.9"

services:
  database:
    image: postgres
    container_name: myMobiDB
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=myMobiAdmin
      - POSTGRES_PASSWORD=tormenta
      - POSTGRES_DB=myMobi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: myMobiBackend
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local